### ISSUE TITLE
Calendar Should be in a week format

### ISSUE THREAD

**Issue by RyanErnst** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#10]
Additional notes: consult recording @ 3 minutes.

**Comment by alexander-bauer** [comment]
I thought that Christie wanted to emphasize dates of events, rather than times, and liked the month format for that?

**Comment by ichniow1** [comment]
The week format, iirc, was something she wanted on a sidebar. Where you could like click the week and get a summary.
