### ISSUE TITLE
Creating admin account: internal server error when you enter information into mentor and semester fields

### ISSUE THREAD

**Issue by ksilber1** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#100]
Does not prompt for password. Simply gives internal server error

**Comment by alexander-bauer** [comment]
@ksilber1 I can't reproduce this, can you give me a little more information?

**Comment by ksilber1** [comment]
As admin, try to create a new admin user, but only input information for name and email, not for password. This gives an internal server error.
