### ISSUE TITLE
Move "week"-view assignments to a sidebar

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#12]
Currently in top navigation bar. Customer requests relocation to side of the page.

**Comment by alexander-bauer** [comment]
Maybe only visible to signed-in users?

**Comment by Mjacks3** [comment]
Gonna close out this issue for now and make a new one for making the assignments (and other data) visible to signed-in users. I want to prioritize and databases/models/forms stuff first.
