### ISSUE TITLE
Add the announcements and administator interface to edit it

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#14]
Pretty open-ended interpretation for now until we implement the admin user functionality. Basically, make the space that will be used for the announcement bar. Whatever looks right to you?

**Comment by alexander-bauer** [comment]
Ideas for this: Administrators can see a textbox populated with plaintext, which gets stored in the database, and rendered into HTML on the front page of any signed-in user. This could be a simple markup format like Markdown, which we can store verbatim in the database, and then render dynamically.

**Comment by alexander-bauer** [comment]
@Mjacks3 They desperately need restyling, but the announcements are now shown on the front page.
