### ISSUE TITLE
Generate week views

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#17]
We need to replace our individual templates for each week with standard forms generated from some kind of data format that the administrators can edit easily without the need to write HTML.

**Comment by alexander-bauer** [comment]
The first step into this is aedc081aab70e7d6a1031501585f49594a79ba3a.

**Comment by Mjacks3** [comment]
@alexander-bauer  

Let me know what the next step of this process is when you get the chance.

**Comment by alexander-bauer** [comment]
@Mjacks3 I think this is going to take some doing; the main trouble is that we need to boil the form creation mechanism down into something Christie can do easily and from the browser, without needing to write any Python or HTML. I think that means we're going to want to dynamically create WTForms classes.

The first thing to do, I think, is to build the interface for creating them, because that's going to be our most complicated piece, and will be the main limiting factor for what we decide that we can accomplish.

As I picture it, this interface should firstly present a textbox for writing free-form introductory text. Then, it should have a document upload section, which allows multiple files, or none. Finally, the assignment creation section, which should allow you to create any number of questions. It should start with zero questions, and have a button to add a new one, of a list of particular types, each of which should have its own interface.

Once the skeleton for the interface exists, we can figure out how to get the data into the database, and how to pre-fill the interface if a given week exists already.
