### ISSUE TITLE
User creation errors cause server exception

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#37]
For example, creating a user which shares an email with an existing user will raise `sqlalchemy.exc.IntegrityError`, and creating a user with an empty password will raise `builtins.ValueError`.

**Comment by Mjacks3** [comment]
@alexander-bauer  is this still an issue? I can't replicate it. 
 If so I may need to switch over to a linux dev env.

**Comment by alexander-bauer** [comment]
@Mjacks3 I'll test in a moment, but if you need a Linux dev environment, you can use the demo site.

**Comment by Mjacks3** [comment]
duplicate of #49
