### ISSUE TITLE
Show actual users on the edit_user_accounts page

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#47]

**Comment by alexander-bauer** [comment]
@Mjacks3 Is there anything left to be done here that we talked about? Because I think they're displayed already.

**Comment by Mjacks3** [comment]
They are displayed, but I was working on allowing the administrator to edit the account information, changing username, password, email and admin status. Password seems to be encrypted. Though this does seem to also fall into the account settings page. Would it be more useful if I just worked on the announcements page first?

**Comment by Mjacks3** [comment]
@alexander-bauer

**Comment by alexander-bauer** [comment]
@Mjacks3 That's definitely more helpful, actually. I'm going to throw together some announcements code right now, though.

**Comment by Mjacks3** [comment]
@alexander-bauer  
Cool. I have to go to sleep tonight, but I'm about halfway done and hope to finish later tomorrow night. Functionally, you can change the name and email for user accounts right now and it works (though changing emails currently creates a new account because of the views logic, which is a bug I will soon fix.)
Can you tell me how to un-hash the password to display it on a form?

**Comment by alexander-bauer** [comment]
@Mjacks3 We should never show users their password after they've created it, and the point of hashing passwords is so that we are actually incapable of doing so; it's a one-way operation.

**Comment by alexander-bauer** [comment]
@Mjacks3 I wanted to also expand on the things I said earlier in person: if we move the individual user editing into their own pages, that will let us "freshen" authentication for normal users before they change their passwords. This is pretty standard practice, and there are some docs [here](https://flask-login.readthedocs.io/en/latest/#fresh-logins).

**Comment by Mjacks3** [comment]
done
