### ISSUE TITLE
Build file upload

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#50]

**Comment by alexander-bauer** [comment]
@UMBC-CMSC447-Spring2017-Team5/developers This is another not-insignificant task that I don't expect to get to soon. I can advise, but anyone willing to do some research should be able to take this. There is a good plugin called Flask-Uploads that should help.

**Comment by RyanErnst** [comment]
If anyone needs info for how to do this, I've found some links that may prove to be helpful.
- [Flask](http://flask.pocoo.org/docs/0.12/patterns/fileuploads/)
- [WebPy](http://webpy.org/cookbook/storeupload/)
- [Runnable](http://code.runnable.com/UiPcaBXaxGNYAAAL/how-to-upload-a-file-to-the-server-in-flask-for-python)

**Comment by alexander-bauer** [comment]
I recommend using the Flask plugin, because that'll integrate more easily, and might already have WTForms integration.

**Comment by RyanErnst** [comment]
Areas of focus collegejump/templates and views.py and forms.py. Needed at file upload and database imports/exports. May also require view for "file upload" and is exclusive for admins.

**Comment by RyanErnst** [comment]
@alexander-bauer, what was the script that you made for creating accounts for us. I can't get passed the login screen.

**Comment by alexander-bauer** [comment]
@RyanErnst It's in `contrib/make_user.py`. You can run it as
```
env/bin/python3 contrib/make_user.py Ryan your@email.com password --admin
```

**Comment by RyanErnst** [comment]
How exactly are we do we want the file to be stored on the website? Shall it be an entry in the database or do we want it as a separate entity?

**Comment by alexander-bauer** [comment]
@RyanErnst there is a Document model in the database that I intended to store it in.

**Comment by alexander-bauer** [comment]
@Mjacks3 I can take this, because I did the file upload for the database. It should only take me a few minutes.
