### ISSUE TITLE
Standardize the url and view naming scheme

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#51]
Some URLs have a `.html` suffix, some do not. Some view names are abbreviated, others are not. We should standardize throughout.

**Comment by alexander-bauer** [comment]
I propose the we un-abbreviate, and remove all html suffixes.

@UMBC-CMSC447-Spring2017-Team5/developers This should be easy to implement across the board.

**Comment by Mjacks3** [comment]
the ~file~.html naming in the render_template() refers to the file name and isn't customize able, correct? Sans that, this issue is completed, reopen if I missed anything.

**Comment by alexander-bauer** [comment]
Looks good to me.
