### ISSUE TITLE
Lowercase emails in all places

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#52]
Currently, emails in different cases will not match. We should make them lowercase everywhere, as is standard.

**Comment by alexander-bauer** [comment]
@UMBC-CMSC447-Spring2017-Team5/developers This is also probably pretty easy.

**Comment by Mjacks3** [comment]
All of two places in the views should be all that's needed, right? Account creation and login? Reopen if needed.

**Comment by alexander-bauer** [comment]
@Mjacks3 I think it might be worth building this into the `User` model, since we might wind up with new ways to create users that would be missed by this, like with the database import. (Admittedly, as long as the data we export is good, that shouldn't be a problem.) There's probably an easy way to do it.

**Comment by Mjacks3** [comment]
Sure. As a heads up, tomorrow I'm gonna need some help switching over to Linux development in order to continue working on issues. My windows environment seems stuck in previous versions, or for whatever reason, just fails to catch up with updates.

**Comment by alexander-bauer** [comment]
I'm going to mark this as an enhancement, since it'd be a nice-to-have, but not something we need to look too hard into right now.

**Comment by Mjacks3** [comment]
Notes:  move user creation email from inside constructor  to outside constructor
