### ISSUE TITLE
Require admin login for some pages

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#53]
Some pages have the `@app.login_required` directive, but do not otherwise check whether the logged in user is an admin.

**Comment by alexander-bauer** [comment]
This can be accomplished by building a similar `admin_required` decorator.

**Comment by Mjacks3** [comment]
@alexander-bauer
 [``]([url](url))![image](https://cloud.githubusercontent.com/assets/22308738/25325947/f3cd2bb6-289b-11e7-84c7-7da8e196f715.png)

**Comment by alexander-bauer** [comment]
@Mjacks3 We're going to have to write this decorator ourselves, but it should be fairly simple.

**Comment by alexander-bauer** [comment]
Since the `@admin_required` directive is implemented now, all that's left to do is make sure editing of accounts is properly locked down. @Mjacks3 can you take care of that?

**Comment by Mjacks3** [comment]
yup. leave it to me!

**Comment by Mjacks3** [comment]
@alexander-bauer 
I tested 
(admin) account creation, editing, deletion and profile editing. all good
(user) profile editing, edit accounts page access, non-self profile access and self deletion. all success

**Comment by alexander-bauer** [comment]
@Mjacks3 I just poked at the code, and it looks good. I'm comfortable closing this.
