### ISSUE TITLE
Create interface for admin syllabus creation

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#56]
- Create/edit semesters
- Create/edit weeks in a semester
-Modify weeks in a semester
-Related to file upload and interface for adding text

**Comment by alexander-bauer** [comment]
Right now, this is the Big Deal, so I'm writing the prototypes for this.

**Comment by Mjacks3** [comment]
@alexander-bauer  sure. Let me know where I can help with this

**Comment by alexander-bauer** [comment]
With recent additions largely in service of #75, I am comfortable calling this task complete.
