### ISSUE TITLE
Non registered email + password submission causes login error.

### ISSUE THREAD

**Issue by Mjacks3** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#66]

**Comment by Mjacks3** [comment]
@alexander-bauer @ksilber1 @ichniow1 

I'm looking on this and I'm not able to reproduce this. Can you give me like a screenshot or a description of how you get this error?

**Comment by alexander-bauer** [comment]
@Mjacks3 I'm not seeing it happen. The logs show an unsuccessful login attempt by an unknown email, which means it's failing down the right path.

**Comment by alexander-bauer** [comment]
@Mjacks3 Since we can't reproduce this, I'm going to close it. If it's still an issue, definitely re-open it.
