### ISSUE TITLE
Make `/` the "primary" url for the index page

### ISSUE THREAD

**Issue by alexander-bauer** [UMBC-CMSC447-Spring2017-Team5/college-JUMP#7]
Currently, `url_for(front_page)` gives the `/index.html` route, which works, but could be cleaner.

**Comment by RyanErnst** [comment]
reference Views.py

**Comment by alexander-bauer** [comment]
I think the only thing necessary to do is swap the order of the `@api.route` calls on the `front_page` function in `views.py`. You can verify that it works by looking at the URL referred to by the "Home" link at the top of the front page. If it ends in `/`, rather than `/index.html`, then it's good.

**Comment by ichniow1** [comment]
this should be resolved unless I'm missing something.
